language: go
go:
  - 1.9

sudo: required

services:
  - docker

script:
  - curl -sL https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 > dep
  - chmod +x ./dep
  - ./dep ensure
  - go test -v ./config ./builders ./utils
